# Java Maven CircleCI 2.0 configuration file
#
#
version: 2
jobs:
  repo-check:
    docker:
      - image: circleci/golang:1.13.8

    working_directory: /go/src/github.com/instaclustr/cassandra-operator
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Validate repository
          command: GO111MODULE=on .circleci/validate_repo.sh
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  build:
    docker:
      # specify the version you desire here
      - image: gcr.io/cassandra-operator/jdk8-gcloud-sdk:2.0.2
        auth:
          username: _json_key
          password: $GOOGLE_AUTH

    working_directory: ~/cassandra-operator

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - m2
            - go-mod-v4-{{ checksum "go.sum" }}

      - setup_remote_docker:
          docker_layer_caching: false

      - run: make

      - save_cache:
          key: m2
          paths:
            - ~/.m2
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"


  release:
    docker:
      # specify the version you desire here
      - image: gcr.io/cassandra-operator/jdk8-gcloud-sdk:2.0.2

    working_directory: ~/cassandra-operator

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      # for helm to be able to use registry feature for push charts
      HELM_EXPERIMENTAL_OCI: 1

    steps:
      - checkout

      - run:
          name: Set TAG environment to version
          command: |
            TAG=$(git tag --points-at master | tail -n 1)
            if [[ ! -z "${TAG}" ]]; then
                echo "export TAG=${TAG}" >> $BASH_ENV
                source $BASH_ENV
            else
                echo "The last commit on master doesn't seem to be tagged! Not releasing"
                circleci-agent step halt
            fi

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - m2
            - go-mod-v4-{{ checksum "go.sum" }}


      # Download and cache dependencies
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Create Docker images
          command: ./buildenv/build-all prod

      - run:
          name: Release docker images
          command: ./buildenv/release-all prod

workflows:
  version: 2
  build_and_test:
    jobs:
      - repo-check
      - build:
          requires:
            - repo-check
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - repo-check
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              only: master
